### ISSUE TITLE
Develop an editable nft collection on Tact

### ISSUE THREAD

**Issue by alefmanvladimir** [getgems-community-tact/nft-template-editable#1]
You can use the current contract template in this repository as a basis. 
Also, see how similar was implemented on func contracts:

1. nft-collection - [contractV1](https://github.com/getgems-io/nft-contracts/blob/main/packages/contracts/sources/nft-collection-editable.fc), [contractV2](https://github.com/getgems-io/nft-contracts/blob/main/packages/contracts/sources/nft-collection-editable-v2.fc)
2. nft-item - [contractV1](https://github.com/getgems-io/nft-contracts/blob/main/packages/contracts/sources/nft-item-editable-DRAFT.fc), [contractV2](https://github.com/getgems-io/nft-contracts/blob/main/packages/contracts/sources/nft-item-editable-v2.fc)

**Comment by hitaspdotnet** [comment]
I like to implement this. It seems that both are the same (#2 & this), since we need the item code for the collection, #2 should be done first, then #1 (this)?
