### ISSUE TITLE
Develop an editable nft item on Tact

### ISSUE THREAD

**Issue by alefmanvladimir** [getgems-community-tact/nft-template-editable#2]
You can use the current contract template in this repository as a basis.
Also, see how similar was implemented on func contracts:

nft-collection - [contractV1](https://github.com/getgems-io/nft-contracts/blob/main/packages/contracts/sources/nft-collection-editable.fc), [contractV2](https://github.com/getgems-io/nft-contracts/blob/main/packages/contracts/sources/nft-collection-editable-v2.fc)
nft-item - [contractV1](https://github.com/getgems-io/nft-contracts/blob/main/packages/contracts/sources/nft-item-editable-DRAFT.fc), [contractV2](https://github.com/getgems-io/nft-contracts/blob/main/packages/contracts/sources/nft-item-editable-v2.fc)

**Comment by hitaspdotnet** [comment]
I like to implement this. It seems that both are the same (#1 & this), since we need the item code for the collection, #1 (this) should be done first, then #2 ?
